### ISSUE TITLE
[front] Criar componente de form

### ISSUE THREAD

**Issue by fernandofleury** [training-center/plataforma-client#10]
A maior parte da aplicação vai girar em torno do form, então precisamos ter alguns tipos bem básicos de componentes pra isso:

- [x] Input
- [x] Label (talvez seguindo material design com o floating label, não sei)
- [x] Select
- [ ] Input com search/autocomplete (Por exemplo pra poder buscar os mentores/pupilos)
- [x] Validação
- [x] Componente wrapper pra se responsabilizar pela validação de todos os campos dentro dele

**Comment by alinebastos** [comment]
Eu pego esta semana, se ninguém mais pegar. Tô gostando do desafio :)
