### ISSUE TITLE
Precisaremos de UX e UI designers

### ISSUE THREAD

**Issue by woliveiras** [training-center/plataforma-client#2]
Visando algo com boa experiência para quem for utilizar nossa plataforma, iremos precisar de UI e UX designers.

Nossa plataforma não precisará ser a última obra de arte de nossas vidas, porém precisaremos ter uma boa experiência de usuário.

Nessa issue precisaremos discutir quantas pessoas ficarão **responsáveis** pelo design da plataforma e quem fará o que.

Lembrando que, depois de iniciado o desenvolvimento, se for necessário que chamemos mais pessoas para ajudar, poderemos chamar sem problemas. :)

**Comment by allangrds** [comment]
Posso contribuir com a construção da UI.

**Comment by woliveiras** [comment]
Manda PR pra nooooes! \o/

Boa, mano!

**Comment by woliveiras** [comment]
Mas com o que temos lá, o que precisamos para desenvolver a UI?

**Comment by joao-alberto** [comment]
@woliveiras Acho que a primeira coisa pra se fazer é um styleguide com todos os componentes, (Button, Switch, Select, Modal, etc).
Da pra usar o [styleguidist](https://github.com/styleguidist/react-styleguidist) ou  o [storybook](https://github.com/storybooks/storybook).

**Comment by woliveiras** [comment]
Consegue montar uma estrutura para começarmos a criar os componentes com essas ferramentas, @joao-alberto?

Já estamos liberados pra começar a fazer essa bagaçeira! https://github.com/training-center/plataforma/issues/6 

:grimacing: :grimacing: :grimacing:

**Comment by joao-alberto** [comment]
@woliveiras Com certeza, crio sim! :metal:

**Comment by khaosdoctor** [comment]
@woliveiras a gente precisa colocar isso tudo em um resumo cara... Ta muito perdido por aqui nas issues kk

**Comment by joao-alberto** [comment]
Eu sugiro que usemos os `projects` do github

**Comment by fernandofleury** [comment]
Vou fechar porque já quebramos em issues.
